import SEO from "../../components/SEO";

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 sm:py-16">
      <SEO
        title="Terms & Conditions"
        description="RentAstra terms of service: user responsibilities, data handling, account usage, and disclaimer."
        path="/terms"
      />
      <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-2">Terms & Conditions</h1>
      <p className="text-sm text-slate-500 dark:text-slate-400 mb-10">Last updated: {new Date().toLocaleDateString()}</p>

      <div className="prose prose-slate dark:prose-invert max-w-none space-y-10">
        <section>
          <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-100 mb-3">User Responsibilities</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            You are responsible for the accuracy of the information you provide and the data you enter into RentAstra. You must use the service in compliance with applicable laws, including those related to tenant data, privacy, and financial records. You must not use RentAstra for any illegal purpose or to store content that infringes others' rights. You are responsible for keeping your login credentials secure and for all activity under your account.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-100 mb-3">Data Handling</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            Data you store in RentAstra (guest details, payments, documents, etc.) is held and processed as described in our Privacy Policy. You retain ownership of your data. We use it only to provide and improve the service. You may export or delete your data in accordance with the functionality we provide. We do not sell your data to third parties.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-100 mb-3">Account Usage Rules</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            One account is intended per user or organization. You must not share your account credentials with others in a way that violates these terms. You may create multiple properties under one account as allowed by the product. We reserve the right to suspend or terminate accounts that violate these terms or that we reasonably believe pose a risk to the service or other users.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-100 mb-3">Disclaimer</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            RentAstra is provided "as is." We do not guarantee uninterrupted or error-free operation. We are not responsible for decisions you make based on data or reports generated by the service (e.g. tax, legal, or compliance). You should verify important information and consult professionals where appropriate. We are not liable for indirect, incidental, or consequential damages arising from your use of the service, to the extent permitted by law.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-100 mb-3">Changes</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            We may update these terms from time to time. Continued use of RentAstra after changes constitutes acceptance of the updated terms. For material changes, we will aim to notify you via the app or your registered email where practicable.
          </p>
        </section>
      </div>
    </div>
  );
}
